### ISSUE TITLE
Ongoing Support

### ISSUE THREAD

**Issue by bsbechtel** [cloudflare/db-connect#10]
This repo is marked as experimental, but the last update was a few months ago. Just curious if it is still being supported or there are future plans for it. Thanks!

**Comment by Electroid** [comment]
Hello! I don't have an update on this right now, but will provide an update once there are some more discussions.

**Comment by Electroid** [comment]
Hello all,

If you're reading this, you probably want to connect your SQL database to Cloudflare Workers. This project was intended to be a stop-gap solution until Workers would support outgoing TCP connections. A time ago, TCP support was a project we were actively working on, but we had to put the project on the shelf because [Unbound](https://blog.cloudflare.com/introducing-workers-unbound/) and [Durable Objects](https://blog.cloudflare.com/introducing-workers-durable-objects/) were more important. 

Is TCP support still a project we want to work on? Absolutely, yes! Is there a time estimate for when it will be done? Unfortunately, no, but once Unbound and Durable Objects are out of beta, we will be a lot closer to that becoming a reality. 

If you *still* want to use this project, you will need to an outdated version of [`cloudflared`.](https://github.com/cloudflare/cloudflared/releases/tag/2021.2.2) Please note, that there will be **no** support for this feature and **no** updates or patches will be provided.
